namespace : default
name : kittyacy-ui
nginxImageOverride : nginxinc/nginx-unprivileged:alpine3.17
imagePullSecret: imagepullSecret
imagePullPolicy: IfNotPresent
replicas: 2
env:
  REACT_APP_API_BASEURL:
    value: 'https://api.kitkube.dk/v1'
  REACT_APP_API_MOCKBASEURL:
    value: 'https://api-mock.kitkube.dk/v1'
  REACT_APP_DISABLE_BUTTONS_NOT_WORKING:
    value: 'false'
  REACT_APP_INACTIVITY_MAX_MINUTES:
    value: '30'
  REACT_APP_KEYCLOAK_CLIENTID:
    value: aftaleportal-ui
  REACT_APP_KEYCLOAK_REALM:
    value: aftaleportal-demo
  REACT_APP_KEYCLOAK_URL:
    value: 'https://keycloak.sdn.t0.hosting.kitkube.dk/auth'
  REACT_APP_NODE_ENV:
    value: production

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Request-Id: $req_id";