{{- $rootValues := .Values }}
{{- range $key, $value := $rootValues.frontendUrls }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Request-Id: $req_id";
  labels:
    app: {{$rootValues.name}}
    app.kubernetes.io/instance: {{$rootValues.name}}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{$rootValues.name}}
    app.kubernetes.io/version: 1.30.2
    argocd.argoproj.io/instance: {{$rootValues.name}}
    helm.sh/chart: service-1.30.2
  name: {{$rootValues.name}}
  namespace: {{$rootValues.namespace}}
spec:
  rules:
    - host: {{$value.url}}
      http:
        paths:
          - backend:
              service:
                name: {{$rootValues.name}}
                port:
                  number: 8080
            path: /
            pathType: Prefix
          - backend:
              service:
                name: {{$rootValues.name}}
                port:
                  number: 3030
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - {{$value.url}}
      secretName: {{$value.url}}
---
  {{- end }}
  